Repository 2024-Winter-Bootcamp-Team-J/frontend, pull requests merged in 2025-01, with the labels that each got.

#2 Chore/#1 개발 초기세팅 완료
  .DS_Store
  .gitignore
  README.md
  eslint.config.js
  index.html
  package.json
  postcss.config.js
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: chore

#4 [fix] git ignore 설정
  .gitignore
Labels: fix

#6 [feat] ci 파이프라인 구축
  .github/workflows/ci.yml
Labels: feat

#8 [fix] git ignore
  .DS_Store
Labels: fix

#10 [chore] 프리티어 세팅
  .github/ISSUE_TEMPLATE/chore.md
  .github/ISSUE_TEMPLATE/design.md
  .github/ISSUE_TEMPLATE/feat.md
  .github/ISSUE_TEMPLATE/fix.md
  .github/ISSUE_TEMPLATE/refactor.md
  .prettierignore
  .prettierrc
  .vscode/settings.json
  eslint.config.js
  package-lock.json
  package.json
  src/App.tsx
  src/Modal/Login.tsx
  src/Modal/Register.tsx
  src/Pages/MainPage.tsx
  src/Pages/StartingPage.tsx
  yarn.lock
Labels: chore

#12 [feat] OnboardingPage, Login, Register 구현틀 마련
  src/App.tsx
  src/Pages/Onboarding.tsx
  src/Pages/StartingPage.tsx
  src/assets/logo.png
Labels: feat

#14 [feat] 메인페이지 뼈대 및 canvas 구현
  package-lock.json
  package.json
  src/Modal/MainPageModal/SideMenu.tsx
  src/Modal/MainPageModal/Typing.tsx
  src/Pages/MainPage.tsx
  src/Pages/Onboarding.tsx
  src/main.tsx
  tsconfig.app.json
  yarn.lock
Labels: feat

#16 [feat] 디렉토리 세팅 및 사이드 메뉴바, 입력창 구현, global.css 설정
  src/ styles/global.css
  src/App.tsx
  src/Modal/MainPageModal/SideMenu.tsx
  src/Pages/MainPage.tsx
  src/components/MainPageComponents/Groups.tsx
  src/components/MainPageComponents/Search.tsx
  src/components/MainPageComponents/Typing.tsx
  src/components/Nods/NewNod.tsx
  src/components/Nods/Nod.tsx
  src/components/SideMenuComponents/Log.tsx
  src/index.css
  src/main.tsx
  tailwind.config.js
Labels: feat

#18 [feat] mainpage 구현
  src/App.tsx
  src/Modal/MainPageModal/SideMenu.tsx
  src/Modal/userModal/Login.tsx
  src/Modal/userModal/Register.tsx
  src/Pages/MainPage.tsx
  src/components/MainPageComponents/Typing.tsx
  src/components/MainPageComponents/locationButton.tsx
  src/main.tsx
Labels: feat

#21 [feat/20] 메인 페이지 관련 퍼블리싱 및 기능 구현
  src/DummyData/Dummy.tsx
  src/DummyData/DummyNod.tsx
  src/DummyData/DummyNodData.tsx
  src/Modal/MainPageModal/SideMenu.tsx
  src/Pages/MainPage.tsx
  src/assets/LocationIcon.png
  src/assets/react.svg
  src/components/MainPageComponents/Groups.tsx
  src/components/MainPageComponents/Search.tsx
  src/components/MainPageComponents/Typing.tsx
  src/components/MainPageComponents/locationButton.tsx
  src/components/Nods/userNod.tsx
  src/components/SideMenuComponents/Log.tsx
  tailwind.config.js
Labels: feat

#23 [feat] 메인페이지 D3.js 차트 구현 완료 및 더미 데이터 적용 완료
  src/DummyData/Dummy.tsx
  src/Pages/MainPage.tsx
  src/components/MainPageComponents/locationButton.tsx
Labels: feat

#26 [feat] 디렉토리 구조 변경
  src/Pages/MainPage.tsx
  src/components/MainPageComponents/SideMenu.tsx
Labels: feat

#29 [feat] onboarding
  src/Pages/Onboarding.tsx
  src/assets/온보딩2.png
Labels: feat

#32 [feat] App.tsx 수정 완료
  src/App.tsx
  src/Pages/Onboarding.tsx
Labels: feat

#35 [feat] 입력 관련 UI 수정 완료
  src/components/MainPageComponents/CategorySelection.tsx
  src/components/MainPageComponents/Typing.tsx
  src/components/Nods/Node.tsx
  tailwind.config.js
Labels: feat

#36 [feat] onboarding
  src/Pages/Onboarding.tsx
  src/assets/온보딩1.png
  src/assets/온보딩3.png
Labels: feat

#40 [feat] 디렉토리 수정, 작업 환경 분리 (Nod 페이지 임시 생성)
  src/App.tsx
  src/Pages/Onboarding.tsx
  src/components/Nods/Nod.tsx
Labels: feat

#43 [feat] 기능 수정 및 구현
  index.html
  src/DummyData/Dummy.tsx
  src/Pages/MainPage.tsx
  src/Pages/Onboarding.tsx
  src/assets/UserIcon.png
  src/assets/logo.png
  src/components/MainPageComponents/D3.tsx
  src/components/MainPageComponents/SideMenu.tsx
  src/components/MainPageComponents/Typing.tsx
  src/components/SideMenuComponents/Log.tsx
  src/components/TypingComponents/ProfileName.tsx
  src/index.css
Labels: feat

#45 [feat] UI 수정
  src/DummyData/Dummy.tsx
  src/Modal/userModal/Login.tsx
  src/Modal/userModal/Register.tsx
  src/Pages/Onboarding.tsx
  src/components/MainPageComponents/D3.tsx
  src/components/MainPageComponents/Typing.tsx
  tailwind.config.js
Labels: feat

#47 [feat] 노드창
  src/App.tsx
  src/Pages/Onboarding.tsx
  src/assets/축소.png
  src/assets/확대.png
  src/components/Nods/Nod.tsx
  src/main.tsx
Labels: feat

#48 [feat] 애니메이션 수정 및 UI 수정
  src/Animation/Typing.css
  src/Modal/userModal/Login.tsx
  src/Modal/userModal/Register.tsx
  src/Pages/MainPage.tsx
  src/Pages/Onboarding.tsx
  src/components/MainPageComponents/CategorySelection.tsx
  src/components/MainPageComponents/Typing.tsx
  src/components/TypingComponents/CategorySelection.tsx
  src/components/TypingComponents/ProfileName.tsx
Labels: feat

#51 [feat] 노드 modal 구현
  src/App.tsx
  src/DummyData/Dummy.tsx
  src/Pages/Onboarding.tsx
  src/components/MainPageComponents/D3.tsx
  src/components/Nods/Nod.tsx
  src/components/Nods/UserNod.tsx
  src/main.tsx
  tailwind.config.js
Labels: feat

#53 [feat] 애니메이션 수정 및 기능 수정
  src/Pages/MainPage.tsx
  src/assets/CloseButton.png
  src/components/MainPageComponents/D3.tsx
  src/components/MainPageComponents/Search.tsx
  src/components/MainPageComponents/SideMenu.tsx
  src/components/MainPageComponents/Typing.tsx
  src/components/Nods/Nod.tsx
  src/components/Nods/UserNod.tsx
  src/components/Nods/UserNodeProfileFriend.tsx
  src/components/TypingComponents/CategorySelection.tsx
  src/components/TypingComponents/ProfileName.tsx
Labels: feat

#56 [feat] 전체적으로 수정
  src/DummyData/DummyNodData.tsx
  src/Modal/Nods/Nod.tsx
  src/Modal/Nods/NodStack.tsx
  src/Modal/Nods/UserNod.tsx
  src/Pages/MainPage.tsx
  src/components/MainPageComponents/D3.tsx
  src/components/MainPageComponents/Typing.tsx
  src/components/Nods/Nod.tsx
  src/components/Nods/UserNodeProfileFriend.tsx
  src/components/TypingComponents/UserNodeProfileFriend.tsx
  src/main.tsx
Labels: feat

#59 [feat] 카테고리 API 연동
  package.json
  src/Modal/Nods/NodStack.tsx
  src/Pages/Onboarding.tsx
  src/components/MainPageComponents/Typing.tsx
  src/components/TypingComponents/CategorySelection.tsx
  yarn.lock
Labels: feat

#60 [feat] 로그인 api
  package.json
  src/Modal/userModal/Login.tsx
  src/Modal/userModal/Register.tsx
  src/Modal/userModal/axiosInstance.ts
  src/Pages/Onboarding.tsx
  yarn.lock
Labels: feat

#63 [feat] real login
  src/Modal/userModal/Login.tsx
Labels: feat

#64 [feat] 관계도 애니메이션, 모든 UI 수정
  src/ styles/global.css
  src/Modal/Nods/Nod.tsx
  src/Modal/userModal/Login.tsx
  src/Modal/userModal/Register.tsx
  src/components/MainPageComponents/D3.tsx
  src/components/MainPageComponents/SideMenu.tsx
  src/components/TypingComponents/ProfileName.tsx
Labels: feat

#67 [feat] 로그인 access/refresh toke 관리 코드 구현
  src/Modal/userModal/Login.tsx
  src/Modal/userModal/LoginStatus.tsx
  src/Modal/userModal/axiosInstance.ts
  src/components/MainPageComponents/SideMenu.tsx
Labels: feat

#69 [feat] 노드설정에서 장고로 변경
  tsconfig.json
  tsconfig.node.json
Labels: feat

#71 [feat] 깃허브 CI 삭제 및 설정 변경
  .github/workflows/ci.yml
  package-lock.json
  package.json
  src/Pages/Onboarding.tsx
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: feat

#72 [feat] 대소무자 구분
  src/modal/Nods/Nod.tsx
  src/modal/Nods/UserNod.tsx
  src/modal/userModal/Login.tsx
  src/modal/userModal/LoginStatus.tsx
  src/modal/userModal/Register.tsx
  src/pages/MainPage.tsx
  src/pages/Onboarding.tsx
Labels: feat

#73 [feat] 대소문자 구분
  src/Pages/MainPage.tsx
  src/Pages/Onboarding.tsx
  src/components/MainPageComponents/LocationButton.tsx
  src/components/MainPageComponents/SideMenu.tsx
  src/modal/UserModal/Login.tsx
  src/modal/UserModal/LoginStatus.tsx
  src/modal/UserModal/Register.tsx
  src/pages/MainPage.tsx
  src/pages/Onboarding.tsx
Labels: feat

#75 [feat] 대소문자 구분
  src/main.tsx
Labels: feat

#77 [feat] 데이터 설계 및 UI 수정
  src/DummyData/Dummy.tsx
  src/Modal/Nods/Nod.tsx
  src/Modal/Nods/UserNod.tsx
  src/components/MainPageComponents/D3.tsx
  src/components/MainPageComponents/Typing.tsx
  src/components/SideMenuComponents/Log.tsx
  src/components/TypingComponents/CategorySelection.tsx
  src/components/TypingComponents/ProfileName.tsx
  src/modal/Nods/Nod.tsx
  src/modal/Nods/NodMemo.tsx
  src/modal/Nods/UserNod.tsx
  src/modal/Nods/UserNodeProfileFriend.tsx
Labels: feat

#82 [feat] create 부분 API 연동 완료
  src/components/MainPageComponents/SideMenu.tsx
  src/components/MainPageComponents/Typing.tsx
  src/components/SideMenuComponents/Log.tsx
  src/components/TypingComponents/CategorySelection.tsx
Labels: feat

#84 [refactor] 카테고리 단일 선택, app.tsx, main.tsx 수정.
  src/App.tsx
  src/Modal/Nods/UserNod.tsx
  src/components/MainPageComponents/Typing.tsx
  src/components/TypingComponents/CategorySelection.tsx
  src/main.tsx
  src/modal/Nods/UserNod.tsx
  src/modal/Nods/UserNodeProfileFriend.tsx
Labels: refactor

#87 Revert "[refactor] 페이지 이름 소문자로 변경"
  src/App.tsx
  src/Modal/Nods/Nod.tsx
  src/Modal/Nods/UserNod.tsx
  src/Pages/MainPage.tsx
  src/Pages/Onboarding.tsx
  src/components/MainPageComponents/D3.tsx
  src/components/MainPageComponents/Search.tsx
  src/components/MainPageComponents/SideMenu.tsx
  src/components/MainPageComponents/Typing.tsx
  src/components/mainPageComponents/d3.tsx
  src/components/mainPageComponents/groups.tsx
  src/components/mainPageComponents/locationButton.tsx
  src/components/mainPageComponents/search.tsx
  src/components/mainPageComponents/sideMenu.tsx
  src/components/mainPageComponents/typing.tsx
  src/components/sideMenuComponents/Log.tsx
  src/components/typingComponents/CategorySelection.tsx
  src/components/typingComponents/ProfileName.tsx
  src/dummyData/Dummy.tsx
  src/modal/Nods/Nod.tsx
  src/modal/Nods/UserNod.tsx
  src/modal/Nods/UserNodeProfileFriend.tsx
  src/modal/nods/nod.tsx
  src/modal/nods/nodMemo.tsx
  src/modal/nods/userNod.tsx
  src/modal/nods/userNodeProfileFriend.tsx
  src/pages/MainPage.tsx
  src/pages/Onboarding.tsx
  src/pages/mainPage.tsx
  src/pages/onboarding.tsx
Labels: fix

#89 Revert "[refactor] 카테고리 단일 선택, app.tsx, main.tsx 수정."
  src/App.tsx
  src/Modal/Nods/UserNod.tsx
  src/components/MainPageComponents/Typing.tsx
  src/components/TypingComponents/CategorySelection.tsx
  src/main.tsx
  src/modal/Nods/UserNod.tsx
  src/modal/Nods/UserNodeProfileFriend.tsx
Labels: fix

#94 [fix] typing 애니메이션
  src/Animation/typing.css
Labels: feat

#97 [feat] 카테고리 완전 수정 완료
  src/components/MainPageComponents/typing.tsx
  src/components/mainPageComponents/typing.tsx
  src/components/typingComponents/categorySelection.tsx
Labels: feat

#101 [feat] 노드 전체 조회, 단일 조회 API 연동 완료
  src/components/mainPageComponent/d3.tsx
  src/components/mainPageComponent/search.tsx
  src/components/typingComponents/categorySelection.tsx
  src/dummyData/dummy.tsx
  src/modals/nod/nod.tsx
  src/modals/nod/nodMemo.tsx
  src/modals/nod/userNod.tsx
  src/modals/nod/userNodeProfileFriend.tsx
  src/modals/nodss/nod.tsx
  src/modals/nodss/nodMemo.tsx
  src/modals/userModal/login.tsx
  src/modals/userModal/loginStatus.tsx
  src/modals/userModal/register.tsx
  src/page/mainPage.tsx
Labels: feat

#104 [feat] relation 이름 id에서 name으로 변경
  src/components/mainPageComponent/d3.tsx
Labels: feat

#107 [refactor] 차트 애니메이션 확실하게 구현 완료, d3코드 분리 완료
  src/components/mainPageComponent/d3.tsx
  src/components/mainPageComponent/d3/d3.tsx
  src/components/mainPageComponent/d3/render.tsx
  src/page/mainPage.tsx
Labels: refactor

#109 Feat/#108 no page reload
  src/assets/generalP.png
  src/components/mainPageComponent/d3/d3.tsx
  src/components/mainPageComponent/d3/render.tsx
  src/modals/nod/generalNod/nod.tsx
  src/modals/nod/generalNod/nodImg.tsx
  src/modals/nod/generalNod/nodMemo.tsx
  src/modals/nod/userNod/userNod.tsx
  src/modals/nod/userNod/userNodeProfileFriend.tsx
Labels: feat

#111 Refactor/#110 existing nod n category
  package.json
  src/components/mainPageComponent/d3/render.tsx
  src/components/mainPageComponent/sideMenuComponent/log.tsx
  src/components/mainPageComponent/sideMenuComponent/sideMenu.tsx
  src/components/mainPageComponent/typingComponents/categorySelection.tsx
  src/components/mainPageComponent/typingComponents/profileName.tsx
  src/components/mainPageComponent/typingComponents/typing.tsx
  src/index.css
  src/modals/nod/generalNod/nod.tsx
  src/modals/nod/generalNod/nodMemo.tsx
  src/page/mainPage.tsx
  tailwind.config.js
  yarn.lock
Labels: refactor

#113 Feat/#112 user id category sort
  package.json
  src/components/mainPageComponent/d3/d3.tsx
  src/components/mainPageComponent/groups.tsx
  src/page/mainPage.tsx
  yarn.lock
Labels: refactor

#115 [feat] 배포 테스트
  src/modals/userModal/login.tsx
Labels: feat

#117 [feat] 로그인 엔드포인트
  src/modals/userModal/login.tsx
Labels: feat

#119 [feat] search api
  src/components/mainPageComponent/search.tsx
  src/page/mainPage.tsx
Labels: feat

#120 [refactor] 시간 형식 바꿈
  package.json
  src/components/mainPageComponent/d3/d3.tsx
  src/modals/nod/generalNod/nodMemo.tsx
  src/modals/userModal/login.tsx
  yarn.lock
Labels: feat, refactor

#122 [refactor] 서치 UI 개선
  src/components/mainPageComponent/search.tsx
Labels: refactor

#124 Refactor/#123 app main tsx refactor
  src/App.tsx
  src/assets/Logo.png
  src/components/mainPageComponent/search.tsx
  src/components/mainPageComponent/sideMenuComponent/log.tsx
  src/components/mainPageComponent/sideMenuComponent/sideMenu.tsx
  src/main.tsx
Labels: refactor

#129 [refactor] 부분 수정
  src/App.tsx
  src/main.tsx
  src/modals/userModal/register.tsx
  src/page/mainPage.tsx
Labels: refactor

#131 [refactor] 토큰 활용해서 user_id의 고유 데이터 분활
  src/components/mainPageComponent/d3/d3.tsx
  src/components/mainPageComponent/search.tsx
  src/components/mainPageComponent/typingComponents/categorySelection.tsx
  src/components/mainPageComponent/typingComponents/typing.tsx
  src/modals/nod/generalNod/nod.tsx
  src/modals/nod/generalNod/nodImg.tsx
  src/modals/userModal/login.tsx
  src/modals/userModal/loginStatus.tsx
Labels: refactor

#133 [feat] 자동화 구현 완료
  src/components/mainPageComponent/typingComponents/typing.tsx
Labels: feat

#135 [feat] API URL 변경
  package-lock.json
  package.json
  src/components/mainPageComponent/d3/d3.tsx
  src/components/mainPageComponent/groups.tsx
  src/components/mainPageComponent/search.tsx
  src/components/mainPageComponent/typingComponents/categorySelection.tsx
  src/components/mainPageComponent/typingComponents/typing.tsx
  src/modals/nod/generalNod/nod.tsx
  src/modals/nod/generalNod/nodImg.tsx
  src/modals/nod/userNod/userNodeProfileFriend.tsx
  src/modals/userModal/register.tsx
  yarn.lock
Labels: refactor

#137 [feat] login, typing API URL 변경
  src/components/mainPageComponent/typingComponents/typing.tsx
  src/modals/userModal/login.tsx
Labels: refactor
